### ISSUE TITLE
Auto minimal-ui?

### ISSUE THREAD

**Issue by Zuti** [gajus/brim#12]
Is it possible to automatically enter minimal-ui (without user interaction)?

If not, is there a way to remember/save minimal-ui setting, so a user does not need to interact on every page (for example on a website with multiple pages - loading a new page resets minimal-ui).

**Comment by TimothyGu** [comment]
> Is it possible to automatically enter minimal-ui (without user interaction)?

Not in iOS 8, which is why this module exists in the first place.
