### ISSUE TITLE
How to install Scream for use with Brim?

### ISSUE THREAD

**Issue by lightmar** [gajus/brim#14]
Hi,

We are developing an HTML5 app and the minimal-ui is a must for us.
But it seems that installing Scream on the server is very complicated.
Is it a must? Is it possible to just copy the Scream JS file, or it must be installed by server-side installation with NodeJS etc...

Thank you!

**Comment by TimothyGu** [comment]
It can be installed through multiple ways, include package managers like [Bower](https://bower.io) and [npm](https://npmjs.org). Directly copying the file should work as well.
