### ISSUE TITLE
Avoid mask with explanation

### ISSUE THREAD

**Issue by daghoidahl** [gajus/brim#15]
We're using iscroll in a project to work around some bugs in Mobile Safari. This disables the "minimal-ui" completely, since the main element never "scrolls", but is moved by iscroll. Brim seems like it could fix that for us, but having a mask element with an explenation that the user must scroll to remove it is an obstacle that we don't want to impose on our users. Is there any way of avoiding that?

**Comment by BrendanBerkley** [comment]
See https://github.com/gajus/brim/issues/12
