### ISSUE TITLE
Relavant in iOS 9?

### ISSUE THREAD

**Issue by metaskills** [gajus/brim#18]
Was talking to a colleague about how the CSS `vh` in iOS 9 now includes the back/forward bottom toolbar and was wondering if the new OS had any meaning to this project. Felt like y'all might know. Thanks in advance!

**Comment by gajus** [comment]
I am not following the question.

Is the minimal-ui relevant to iOS 9? Absolutely. iOS 9 does not support minimal-ui.

**Comment by gajus** [comment]
Does brim work with iOS 9? I have not tested, but it should. Brim is used in quite a few projects. There would have been complaints if it did not work.

**Comment by metaskills** [comment]
> There would have been complaints if it did not work.

Thanks. I did search the issue for iOS 9 and found nothing. Today I was introduced to a bug WRT the `vh` property and even tho I do not see that used in this project, I thought I would ask. Cheers.

**Comment by gajus** [comment]
Sorry, due to the nature of the script, there is no way to automate the test cases.
