### ISSUE TITLE
iPad Pro not recognised

### ISSUE THREAD

**Issue by CraigBeswetherick** [gajus/brim#19]
When emulating an iPad Pro, the "device not recognised" error is thrown. The issue that it links to has been closed, so I am creating a new one. I am using xCode to emulate the device. 

The user agent is as follows:

Mozilla/5.0 (iPad; CPU OS 9_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13C75 Safari/601.1

**Comment by CraigBeswetherick** [comment]
Ok, so adding a definition for the iPad Pro in the scream spec helped:

[2048, 2604, 2732, 1920, 1024, 1366, 2, 'iPad Pro']

The values in the spec for the iPhone 6 etc - how where they calculated? I need to set the same ones for window.innerWidth & window.innerHeight for the iPad Pro, but the value of window.innerWidth of the iPhone 6 for instance is much different to what is in the  scream spec. If you could let me know how they where calculated I can make a PR

**Comment by gajus** [comment]
> The values in the spec for the iPhone 6 etc - how where they calculated?

https://github.com/gajus/scream/blob/master/.spec/ruler.js

**Comment by gajus** [comment]
Capturing these values is not automated though:

1. Use an emulator to run iPad Pro
1. Use https://github.com/gajus/scream/blob/master/.spec/ruler.js to capture device information in all states (e.g. https://github.com/gajus/scream/blob/master/.spec/iPhone%206.txt)
1. Create a spec file https://github.com/gajus/scream/tree/master/.spec
1. Add definition to https://github.com/gajus/scream/blob/cfde779a7730c0c9c31c18710dfb12989ca8a56e/src/scream.js#L139-L152

**Comment by CraigBeswetherick** [comment]
Thanks for the help :) 

PR submitted: https://github.com/gajus/scream/pull/8
