### ISSUE TITLE
NPM error when searching for `gajus.Scream`!

### ISSUE THREAD

**Issue by RafaelPlantard** [gajus/brim#29]
https://github.com/gajus/brim/blob/809d68475504aa2482fadca1d90cb7620fb11bbd/src/brim.js#L19

**Comment by gajus** [comment]
NPM error? Not clear what you are asking for.

Closing until further details provided.

**Comment by RafaelPlantard** [comment]
@gajus I'm trying to use `Scream` + `Brim` with webpack into a Vue.JS system, but when I try to create an instance of Brim, using the following code:
```
const scream = Scream({
    width: {
        portrait: 320,
        landscape: 568
    }
});

const brim = Brim({
    viewport: scream
});
```

The brim instance has not been created because of this:
https://github.com/gajus/brim/blob/809d68475504aa2482fadca1d90cb7620fb11bbd/src/brim.js#L19

For some reason the `Scream` from NPM package is not same of `gajus.Scream` instance.
Any idea of how to solve it?

**Comment by gajus** [comment]
Have you inspected the contents of the entry point of those scripts?, i.e. look at the package.json main value and what script that executes.

I have not touched Scream/ Brim in a long time.

**Comment by gajus** [comment]
Oh, I see. This line of code was from Brim.

https://github.com/gajus/brim/blob/809d68475504aa2482fadca1d90cb7620fb11bbd/src/brim.js#L19-L21

Yeah, this obviously does not make sense.

Looks like the only fix would be to add `scream` as a dependency of Brim and check instanceof of the imported dependency.

**Comment by RafaelPlantard** [comment]
Thanks a lot @gajus 
It works ;D

**Comment by RafaelPlantard** [comment]
Hey @gajus thanks for this update, but apparently isn't working:
<img width="1280" alt="screen shot 2017-09-01 at 00 14 04" src="https://user-images.githubusercontent.com/5968478/29953966-8f2ea3fe-8eaa-11e7-833e-87785ebd3a5d.png">

I run it before: `npm update`:
`"brim": "^1.0.12",`

**Comment by gajus** [comment]
Can you try to look into the code?

I am out of capacity to take on this at the moment.

**Comment by gajus** [comment]
I am fine with the `instanceof` check being completely removed.

**Comment by RafaelPlantard** [comment]
Actually, it will be my next suggestion, haha, just check for not null value and remove instance of check.
